apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

# Base resources
resources:
- ../../manifests/api1-deployment.yaml
- ../../manifests/api1-service.yaml
- ../../manifests/web1-deployment.yaml
- ../../manifests/web1-service.yaml
- ../../manifests/ingress.yaml
- namespace.yaml

# Common labels
commonLabels:
  environment: prod
  team: web-api

# Images
images:
- name: localhost:5000/api1
  newTag: latest
- name: localhost:5000/web1
  newTag: latest

# Patches for production environment
patchesStrategicMerge:
- api1-deployment.yaml
- web1-deployment.yaml
- ingress.yaml

# ConfigMap generator
configMapGenerator:
- name: app-config
  literals:
  - environment=production
  - debug=false
  - api_url=https://api.yourdomain.com

# Resource configuration for production
replicas:
- name: api1-deployment
  count: 3
- name: web1-deployment
  count: 3